services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
  web:
    image: adminer
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: winkwink
  mongo:
    image: mongo
